{
 "title": "infra-overview",
 "description": "infra-overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top containers CPU",
   "type": "barchart",
   "description": "Shows which containers are consuming the most CPU in real time.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, rate(container_cpu_usage_seconds_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top containers memory",
   "type": "barchart",
   "description": "Top containers memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, container_memory_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "Disk I/O",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total[1m]) + rate(container_fs_writes_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}