{
 "title": "n8n Health Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active workflows",
   "type": "stat",
   "description": "Shows how many workflows are currently active",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "n8n_active_workflow_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "stat",
   "description": "Converts process start time into “uptime” trend.\nShows how long n8n has been running",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - n8n_process_start_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Shows CPU usage over time.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(n8n_process_cpu_seconds_total[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "gauge",
   "description": "Actual memory in RAM",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "n8n_process_resident_memory_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of heap used",
   "type": "gauge",
   "description": "Detects memory saturation before OOM errors.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "n8n_nodejs_heap_size_used_bytes / n8n_nodejs_heap_size_total_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Loop Latency (p99)",
   "type": "timeseries",
   "description": "High values = workflows getting stuck, Node.js overloaded.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "n8n_nodejs_eventloop_lag_p99_seconds",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}